"""朔と二十四節気を一括計算してCSVにする（開発時のみ）。

    PYTHONPATH=src python3 -m almanac_calendar._generate.gen_koyomi_tables

配布物には入らない。`ephem` を使うのはここだけで、実行時（利用者のランナー）は
標準ライブラリのみでこのCSVを読む。

**視黄経の求め方に3つの落とし穴がある**（2026-08-01に実測で確認）:

  1. `ephem.Ecliptic(sun)` の既定は **J2000基準**。歳差ぶん約9時間ずれる
     （2026年で0.363度＝約523分）
  2. `epoch=当日` にしても `a_ra/a_dec`（astrometric）のままだと光行差・章動が
     抜けて約6分ずれる（約15秒角）
  3. 正解は **`g_ra`/`g_dec`（見かけの地心位置）を日付の分点で黄道座標に直す**。
     これで国立天文台の公表値と誤差0.2分に収まる

朔は `ephem.next_new_moon` が内部で正しく扱うのでそのまま使える。

出力は **UTC**。天文現象は子午線に依存せず、暦日の割り当てだけが依存するので、
同じテーブルを他の暦体系（中国 UTC+8 等）にも使える。
"""
from __future__ import annotations

import datetime as dt
import math
import sys
from pathlib import Path

import ephem

OUT_DIR = Path(__file__).resolve().parent.parent / "assets" / "koyomi"

# 生成範囲。サポート範囲（1900-01-01〜2100-12-31）は**冬至から冬至までの
# 1周期でぴったり挟まれていなければならない**。月名も閏月の位置も、冬至月を
# 起点に次の冬至月まで数えて初めて決まるため、片側でも欠けるとその周期は
# まるごと配置できない。
#   前: 1899-12-22の冬至と、それを含む朔望月の朔（1899-12-03）が要る
#   後: 2100-12-31は2100-12-21の冬至の後にあるので、**2101-12-22の冬至**と
#       その次の朔まで要る。2101-04で切ると2100-12-31が最後の月からはみ出て
#       「31日」になる（実際にそうなった）
GEN_START = dt.datetime(1899, 11, 1, tzinfo=dt.timezone.utc)
GEN_END = dt.datetime(2102, 3, 1, tzinfo=dt.timezone.utc)

LONGITUDE_DEFINITION = "apparent geocentric (g_ra/g_dec), equinox of date"


def _to_utc(e: ephem.Date) -> dt.datetime:
    y, mo, d, h, mi, s = e.tuple()
    naive = dt.datetime(y, mo, d, h, mi) + dt.timedelta(seconds=round(s))
    return naive.replace(tzinfo=dt.timezone.utc)


def _to_second(when: dt.datetime) -> dt.datetime:
    """秒までを残す。**分に丸めてはいけない。**

    国立天文台の公表値は分単位なので、以前はここで四捨五入していた。それが
    日界をまたぐ現象で日付を動かしていた——2030年の雨水は真の値が
    23:59:40 JST（2月18日）なのに、丸めると 00:00（2月19日）になる。
    NAOJは同じ分単位でも `2030/02/18 24:00` と書いて**日付のほうを保持する**。

    日付の割り当ては暦の契約そのもの（節月の境界・月相の表示日が動く）なので、
    表示の都合で丸めた値を根拠にしてはいけない。分単位の比較が要るところは
    読む側で丸める。
    """
    return when.replace(microsecond=0)


def sun_longitude(when: ephem.Date) -> float:
    """太陽の視黄経（度）。落とし穴3点はモジュール冒頭を参照。"""
    sun = ephem.Sun()
    sun.compute(when)
    equatorial = ephem.Equatorial(sun.g_ra, sun.g_dec, epoch=when)
    return math.degrees(float(ephem.Ecliptic(equatorial).lon))


#: 月相のコード。朔弦望の順で、月と太陽の離角 0/90/180/270度に対応する。
#: 数値で持つのは、表示名が言語ごとに変わるのに対しこれは暦法の識別子だから。
PHASE_FINDERS = (
    (0, ephem.next_new_moon),        # 朔（新月）
    (1, ephem.next_first_quarter_moon),   # 上弦
    (2, ephem.next_full_moon),       # 望（満月）
    (3, ephem.next_last_quarter_moon),    # 下弦
)


def moon_phases() -> list[tuple[dt.datetime, int]]:
    """朔弦望すべて。朔だけでなく四相を持つ理由は2つある。

    1. **月の形の描画に要る**。輝面比を月齢から線形に出すと、月の軌道が
       楕円で不等速なぶん誤差が出る（望は月齢13.9〜15.6日の幅で起きる）。
       離角が厳密に分かっている四相の間を補間すれば、少なくとも
       四相ちょうどでは 0/50/100/50% と厳密に一致する。
    2. **検証が濃くなる**。国立天文台の朔弦望表には四相とも載っているので、
       同じ1回の取得で照合件数が4倍になる。
    """
    out: list[tuple[dt.datetime, int]] = []
    for code, finder in PHASE_FINDERS:
        cursor = ephem.Date(GEN_START.strftime("%Y/%m/%d"))
        while True:
            cursor = finder(cursor)
            when = _to_second(_to_utc(cursor))
            if when > GEN_END:
                break
            out.append((when, code))
    return sorted(out)


def _crossing(target: float, lo: ephem.Date, hi: ephem.Date) -> dt.datetime:
    """黄経が target を通過する瞬間を二分探索で詰める。"""
    def offset(when: ephem.Date) -> float:
        return ((sun_longitude(when) - target + 180) % 360) - 180

    for _ in range(60):
        mid = ephem.Date((lo + hi) / 2)
        lo, hi = (mid, hi) if offset(mid) < 0 else (lo, mid)
    return _to_second(_to_utc(ephem.Date((lo + hi) / 2)))


def solar_terms() -> list[tuple[dt.datetime, int]]:
    """24節気すべて（15度刻み）。中気だけでなく節気も持つ。

    中気は閏月判定に、節気も含む全24個は将来の表示（S5b）に使う。
    1日刻みで走査して30度境界の通過を検出し、そこを二分探索で詰める。
    太陽は1日に約1度しか動かないので、1日刻みで取りこぼしは起きない。
    """
    out: list[tuple[dt.datetime, int]] = []
    cursor = ephem.Date(GEN_START.strftime("%Y/%m/%d"))
    end = ephem.Date(GEN_END.strftime("%Y/%m/%d"))
    previous = sun_longitude(cursor)
    while cursor < end:
        nxt = ephem.Date(cursor + 1)
        current = sun_longitude(nxt)
        # 15度の倍数をまたいだか。0度をまたぐ折り返しも扱う
        crossed = int(previous // 15) != int(current // 15) or current < previous
        if crossed:
            target = (int(previous // 15) + 1) * 15 % 360
            when = _crossing(target, cursor, nxt)
            out.append((when, target))
        cursor, previous = nxt, current
    return out


def _write(path: Path, header: list[str], rows: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(header + rows) + "\n", encoding="utf-8")


def main() -> int:
    meta = [
        "# generated by almanac_calendar/_generate/gen_koyomi_tables.py — do not hand-edit",
        f"# ephem: {ephem.__version__}",
        f"# longitude: {LONGITUDE_DEFINITION}",
        f"# range: {GEN_START:%Y-%m-%d} .. {GEN_END:%Y-%m-%d} (UTC, second resolution)",
        "# supported: 1900-01-01 .. 2100-12-31",
    ]

    phases = moon_phases()
    _write(OUT_DIR / "moonphases.csv", meta + ["utc,phase"],
           [f"{w:%Y-%m-%dT%H:%M:%S},{code}" for w, code in phases])
    print(f"moonphases.csv: {len(phases)}件"
          f"（朔 {sum(1 for _, c in phases if c == 0)}）")

    terms = solar_terms()
    _write(OUT_DIR / "solarterms.csv", meta + ["utc,longitude"],
           [f"{t:%Y-%m-%dT%H:%M:%S},{lon}" for t, lon in terms])
    print(f"solarterms.csv: {len(terms)}件")
    return 0


if __name__ == "__main__":
    sys.exit(main())
