"""各国の祝日テーブルを生成する（開発時のみ）。

    PYTHONPATH=src python3 -m almanac_calendar._generate.gen_holidays [US GB KR ...]

`holidays`（MIT・501の国コード）をビルド時だけ使い、実行時は標準ライブラリで
CSVを読むだけにする。暦テーブルと同じ構成（ADR-0011 不変条件7）。

**日本はここで生成しない**。`koyomi/holidays_jp.py` に法の規則として実装して
ある。理由は春分の日・秋分の日で、法律には日付が書かれておらず「春分日」と
だけ定められている。実体は天文現象なので、NAOJと全件照合済みの節気テーブルから
引くほうが確実で、しかも `holidays` の日本対応は2099年で切れるが節気テーブルは
2100年まである。祝日法の日付規則のほうは `verify_holidays_jp.py` で
`holidays` と全件照合しており、1949〜2099年は完全に一致している。

祝日は法改正で変わる。生成日とライブラリのバージョンをヘッダに残し、
**いつの法令に基づく表かを後から辿れるようにする**。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import holidays

OUT_DIR = Path(__file__).resolve().parent.parent / "assets" / "holidays"

#: 既定で生成する国。増やすのは引数を足すだけでよい。
#: 全501カ国を同梱しないのは、1カ国あたり約45KBあり、使わない国まで
#: 配布物に載せる理由がないため
DEFAULT_COUNTRIES = ("US", "GB", "KR", "CN", "TW", "DE", "FR", "SG")

#: 生成範囲。ウィジェットが描くのは今の前後なので、暦テーブルほど広く取らない。
#: 祝日は法改正で変わるので、遠い将来の値は「現行法が続いたら」でしかない
YEARS = range(2000, 2101)


def generate(code: str) -> int:
    rows: list[str] = []
    for year in YEARS:
        try:
            found = holidays.country_holidays(code, years=[year])
        except NotImplementedError:
            raise SystemExit(f"未対応の国コードです: {code}")
        for day, name in sorted(found.items()):
            if day.year != year:
                continue
            # 名前に改行やカンマが入りうる。CSVを壊さないよう潰す
            label = name.replace(",", "、").replace("\n", " ").strip()
            rows.append(f"{day.isoformat()},{label}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = [
        "# generated by almanac_calendar/_generate/gen_holidays.py — do not hand-edit",
        f"# holidays: {holidays.__version__}",
        f"# country: {code}",
        f"# range: {YEARS.start} .. {YEARS.stop - 1}",
        "# note: 祝日は法改正で変わる。上のバージョンが基づいた法令の時点",
        "date,name",
    ]
    (OUT_DIR / f"{code}.csv").write_text("\n".join(header + rows) + "\n", "utf-8")
    return len(rows)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="各国の祝日テーブルを生成する")
    p.add_argument("countries", nargs="*", default=list(DEFAULT_COUNTRIES),
                   help=f"ISO 3166-1 alpha-2（既定: {' '.join(DEFAULT_COUNTRIES)}）")
    args = p.parse_args(argv)
    for code in args.countries or DEFAULT_COUNTRIES:
        code = code.upper()
        if code == "JP":
            print("JP はスキップします（koyomi/holidays_jp.py に実装済み）")
            continue
        print(f"{code}.csv: {generate(code)}件")
    return 0


if __name__ == "__main__":
    sys.exit(main())
